### ISSUE TITLE
Mercator projection removes Russia

### ISSUE THREAD

**Issue by matsimitsu** [martinfrances107/rust_d3_geo#31]
Hi there, awesome library! 

I'm trying to render an SVG map of the world, but it seems I can't get Russia to render. 
![map](https://github.com/martinfrances107/rust_d3_geo/assets/28408/670d9b67-d391-4933-be47-9b2c7beb6ffc)

If I add `clip_angle_set` it does render the country, but that cuts off half the map. 
![map](https://github.com/martinfrances107/rust_d3_geo/assets/28408/04b33e71-35e1-4690-828c-786e8a6596b4)

I suspect it has to do with clipping and Russia wrapping around, but I'm not versed in D3, nor Rust enough to figure it out. 

I've build a reproduction repo here: https://github.com/matsimitsu/map-issue

Any idea's what it could be? 

[edit]
My end goal would be to generate maps like these for a website by calling an endpoint, instead of calculating and rendering this in the browser (e.g. make it mobile friendly).

![Screenshot 2023-07-11 at 23 04 16](https://github.com/martinfrances107/rust_d3_geo/assets/28408/0fb1c2da-9e6e-443a-a1f4-78e6f9498bde)

**Comment by martinfrances107** [comment]
Hi, thanks for reporting the issue... I will spend a little time over the weekend on this...

I am just making a list of things for myself ( might as well make the notes public)  .. things I am going to investigate

1) [Mercators has a known issue]( https://github.com/martinfrances107/rust_d3_geo/issues/17)

    When comparing the RUST and Javascript projection, I know that the  rust version renders the 
    eastern seaboard of the USA incorrectly.

    Under Orthgraphic projection does the issue persist?
    Can I use the eventual answer here to probe that issue.

2) I need to verify the integrity of the input JSON in the PR 

   Is  the  RUSSIA polygon valid /  correctly closed. 
   Can I strip out the all the other polygons?
   Can I replace the map input with a known golden reference.

More .. later.

**Comment by martinfrances107** [comment]
Just a micro update ... I am just making comments in public when I see something interesting 

I have forked "map issue"  and started making changes [ here  ](https://github.com/martinfrances107/map-issue)

I created a stripped down version of world.json will all countries BUT russia removed.
( its called russian.json) 

When I put russia.json into a online visualisation tool [geojson.tools](https://geojson.tools/)

I can see the perimeter of "Russia",  So I think the rust_d3_geo  library should at least be rendering the outline. The information is definitely contained in the input   

I also notes that visually it looks broken.

My experience with geojson parsers is troubled, transferring files form vendor the vendor frequently leads to these flaws.

Anyway more from me as i see it.

**Comment by martinfrances107** [comment]
Just collecting data points -  In my fork I created a new branch "ortho"

I swapped out the Mercator projection for Orthographic and tweaked the rotation so the images is centred on Russia 

Yep the outline show up with issue.

https://github.com/martinfrances107/map-issue/blob/ortho/ortho.svg

**Comment by matsimitsu** [comment]
For what it's worth, I initially used the 50m file from this project, and it was also not showing up.

I switched to the map included in my example, because I knew it rendered when using d3, e.g. thats the map I use for my "current" (JS) map code. 

In Rust, I'm now using the `Equirectangular` projection and it renders the map as I expect. 

ps. I'm super happy with this library, as it made a lot of front-end code obsolete. Instead of half a megabyte of front-end code that still needs to fetch the 400 kilobyte world map, I now emit a couple of bytes of SVG instead.

**Comment by martinfrances107** [comment]
Progress, I have just pushed  a stripped down unit test that exposes the issue 

So now we can compare the behaviour of the java script library to ours.

I will debug this later in the week.

**Comment by martinfrances107** [comment]
> ps. I'm super happy with this library, as it made a lot of front-end code obsolete.

Thanks for saying that ... My focus is on  getting animation with  high resolution maps to work.. currently I am getting only about a 30% speedup,  with that boost - so you see lots of janky motion of mobiles... I had not really considered the server side and page weight arguments... It is good to be shaken out of ones perspective.

**Comment by martinfrances107** [comment]
I will keep this open until I understand the issues associated with the unit test

**Comment by martinfrances107** [comment]
Just published version 1.0.6 - with the bugfix.

> I've build a reproduction repo here: https://github.com/matsimitsu/map-issue

I Can confirm 1.0.6 makes the perimeter of Russia visible on the reproduction repo.

**Comment by martinfrances107** [comment]
As of this commit https://github.com/martinfrances107/rust_d3_geo/commit/2ba5fd8730a0dda2c1ce7d31d27b735c6bc0fbb7
 
 The test which covers the bugfix is now active in the test suite.


The doc issue is being tracked elsewhere.

So I am closing this as complete.
 
Thanks again for the report .. it fixed a long standing issue in example/projection

**Comment by matsimitsu** [comment]
Awesome, thank you!
